const NAME = 'name';
const KEY = 'key';
const CREATED_AT = 'createdAt';
const EXPIRE_AT = 'expireAt';
const STATE = 'state';

const DESCENDING_SORT = 'DESC';
const ASCENDING_SORT = 'ASC';

const INITIAL_TOKEN_LIMIT = 25;
const INITIAL_OFFSET = 0;

const REFETCHER_MAP = new Map();
const TOKENS_REFETCH_KEY = 'tokensRefetcher';

export {NAME, KEY, CREATED_AT, EXPIRE_AT, STATE, INITIAL_OFFSET, INITIAL_TOKEN_LIMIT, DESCENDING_SORT, ASCENDING_SORT, REFETCHER_MAP, TOKENS_REFETCH_KEY};
