const USERNAME = 'user.name';
const NAME = 'name';
const KEY = 'key';
const CREATED_AT = 'createdAt';
const EXPIRE_AT = 'expireAt';
const STATE = 'state';

const DESCENDING_SORT = 'DESC';
const ASCENDING_SORT = 'ASC';

const INITIAL_TOKEN_LIMIT = 25;
const INITIAL_OFFSET = 0;

const POLL_INTERVAL = 5000;

export {USERNAME, NAME, KEY, CREATED_AT, EXPIRE_AT, STATE, INITIAL_OFFSET, INITIAL_TOKEN_LIMIT, POLL_INTERVAL, DESCENDING_SORT, ASCENDING_SORT};
